#+TITLE: Writing Testable Code: JavaScript and TypeScript Edition
#+AUTHOR: Donatas Petrauskas
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" href="org/style.css" type="text/css">

* Preface

# Why did I write this article?

I spend substantial amount of time writing tests and as a consequence learning
about software design in a process. I usually learn most from my own mistakes,
as it is hard to understand abstract ideas unless presented with concrete
examples. But from time to time I would find some article or video that
resonates and I think is worth sharing with others. In this post I'd like to
summarize and discuss "Guide: Writing Testable Code"[fn:2] from Miško Hevery of
AngularJS fame.

The reason why I actually spent reading this pretty long document and watched
Google Tech Talks on testable code[fn:1] is that my career as front-end
developer started with AngularJS about 5 years ago. The great thing with
AngularJS at that time was that it introduced architecture that made it hard not
to write testable code. It took me a couple of years to appreciate what
AngularJS offered and to really grasp it's potential[fn:5]. I lacked
understanding of a guiding principles laid out in Miško's articles. Once I
understood those, it became clear what constitutes testable code. It didn't
become easy to write, though.

# What is my goal with this article?

My hope with this article is to channel Miško's ideas and give you, dear reader,
cognitive tools for recognizing untestable code.

/Note/: In this article I will be using TypeScript and JavaScript for examples, but
rules are universal and can be applied to other languages. Even purely
functional ones. But to be fair, purely functional languages, like Elm, makes it
really really hard to write untestable code.

* About "Guide: Writing Testable Code"

"Guide: Writing Testable Code" was written as internal document at Google
targeting Java code. Many of given examples are very much tied to Java and
Dependency Injection framework Guice. But the underlying ideas are applicable to
TypeScript and JavaScript nonetheless.

Guide consists of 4 parts (flaws):
1. "Constructor does Real Work"
2. "Digging into Collaborators"
3. "Brittle Global State & Singletons"
4. "Class Does Too Much"

Parts 2 to 4 are kind of obvious, but we will go through them anyway. While part
1 is definitely a common sense one, I don't think I ever saw it mentioned and
pointed out so clearly before. Making your constructors dumb is very important
for objects to be testable. Moreover, it also has this nice consequence of
forcing your app or module to have clearly separated initialization and
execution phases.

** Digging into Collaborators

This one is very easy to spot. For example, if we see a second level access of
property in your code like this

#+BEGIN_SRC javascriptn
this.session.getAccount().getNickname()
#+END_SRC

we have a problem. It will become clear when writing a test for it. We will have
to either mock or construct =Account= in addition to =Session= in all places where
=Session= is a dependency. Renaming a method of =Account= will impact places where
direct dependency is =Session=, not =Account=. While most IDEs have no problem with
renaming, your code revision history will become noisy.

Let's take a look at the following example.

#+BEGIN_SRC javascript
function StatusBar({session, onLogout}) {
  const name = getName(getAccount(session));
  return (
    <div>Hello, {name}! <button onClick={onLogout}>Logout</button></div>;
  );
}

function Avatar({session}) {
  const account = getAccount(session);
  const profilePictureUrl = getProfilePicture(account);
  const name = getName(account);
  return (
    <div><img src={profilePictureUrl}/><span>{name}</span></div>
  );
}
#+END_SRC

Instead of chains of method calls, we have nested selectors[fn:6] exhibiting the
same issue. To avoid digging into =session=, we might introduce =getAccountPicture=
and =getAccountName= methods. Another solution is to not pass whole =session= to
these simple components, but that would defeat the purpose of this example.

** Global state
Global state is sneaky. It hides under multiple names: mutable variables, static
methods, singleton objects, and any dependencies that are not passed as
arguments. Global state is infectious. Single instance of it in small module
will corrupt all of your application.

Main point I want you take away is that global state might not be
obvious. Singleton pattern in OOP is well spread practice, so how come it is
bad? Well, if there is a need to test or try small portion of code in a REPL, it
will become clear how bad it actually is.

Let's take a look at small example of sneaky global state.

#+CAPTION: Cache module.
#+BEGIN_SRC javascript :tangle "src/global-state/bad/cache.js"
const cache = {};

function set(key, value) {
  return cache[key] = value;
}

function get(key) {
  return cache[key];
}

module.exports = {
  set,
  get,
};
#+END_SRC

#+CAPTION: Utility to fetch posts.
#+BEGIN_SRC javascript :tangle "src/global-state/bad/fetch-posts.js"
const fetch = require('node-fetch');
const cache = require('./cache');

const BASE_URL = 'http://localhost:8080';

async function fetchPosts(since) {
  const timestamp = since.getTime();
  const KEY = 'posts_since_' + timestamp;
  let posts = cache.get(KEY);
  if (posts == null) {
    const response = await fetch(BASE_URL + '/posts?since=' + timestamp);
    if (response.status === 200) {
      posts = await response.json();
      cache.set(KEY, posts);
    } else {
      return {error: 'Cannot fetch posts'};
    }
  }
  return {result: posts};
}

module.exports = {
  fetchPosts,
};
#+END_SRC

#+CAPTION: Complicated tests.
#+BEGIN_SRC javascript :tangle "src/global-state/bad/fetch-posts.test.js"
const test = require('tape');
const proxyquire = require('proxyquire');

test('fetchPosts()', async (assert) => {
  const expectedPosts = [1, 2, 3];
  const expectedError = 'Cannot fetch posts';
  let fetchPostsModule = proxyquire('./fetch-posts', {
    'node-fetch': (url) =>
      Promise.resolve({status: 200, json: () => Promise.resolve(expectedPosts)})
  });

  assert.deepEqual(
    await fetchPostsModule.fetchPosts(new Date()),
    {result: expectedPosts},
    'successfully fetches posts'
  );

  fetchPostsModule = proxyquire('./fetch-posts', {
    'node-fetch': (url) => Promise.resolve({status: 500})
  });

  assert.deepEqual(
    await fetchPostsModule.fetchPosts(new Date()),
    {error: expectedError},
    'returns empty array and error on failure'
  );

  assert.end();
});
#+END_SRC

Great success!?

#+BEGIN_SRC sh :exports results :results output
(node src/global-state/bad/fetch-posts.test.js | ./node_modules/.bin/tap-spec) 2>&1
true
#+END_SRC

#+RESULTS:
#+begin_example

  fetchPosts()

    ✔ successfully fetches posts
    ✔ returns empty array and error on failure


  total:     2
  passing:   2
  duration:  25ms


#+end_example

Not really. Even though tests have passed, we had to use proxyquire[fn:3] to tap
into module system and override dependencies. This a neat trick, but ultimately
it's a sign of global state issue. Modules are singletons, they're run only
once. Even though it's pretty common to see such code in a wild, it's not
testable or REPL friendly.

There is another catch -- our tests are only accidentally successful. If they
would run fast enough to produce the same timestamp, we would get data served
from the cache, which is a singleton object for whole application.

What would testable code look like?

First, cache module exposes a function to create one.

#+CAPTION: Cache module.
#+BEGIN_SRC javascript :tangle "src/global-state/good/cache.js"
function Cache() {
  const store = {};

  function set(key, value) {
    return store[key] = value;
  }

  function get(key) {
    return store[key];
  }

  return {
    set,
    get,
  };
}

module.exports = Cache;
#+END_SRC

The same goes for utility to fetch posts. It's a repository object now, that can
be configured with all it's dependencies.

#+CAPTION: Posts repository object.
#+BEGIN_SRC javascript :tangle "src/global-state/good/posts-repo.js"
function PostsRepo(BASE_URL, fetch, cache) {
  async function query(since) {
    const timestamp = since.getTime();
    const KEY = 'posts_since_' + timestamp;
    let posts = cache.get(KEY);
    if (posts == null) {
      const response = await fetch(BASE_URL + '/posts?since=' + timestamp);
      if (response.status === 200) {
        posts = await response.json();
        cache.set(KEY, posts);
      } else {
        return {error: 'Cannot fetch posts'};
      }
    }
    return {result: posts};
  }

  return {
    query,
  }
}

module.exports = PostsRepo;
#+END_SRC

As a result, we no longer need proxyquire. It's also painfully clear, that we
have a cache, and we should be careful with it.

#+CAPTION: Complicated but honest tests.
#+BEGIN_SRC javascript :tangle "src/global-state/good/posts-repo.test.js"
const test = require('tape');

const Cache = require('./cache');
const PostsRepo = require('./posts-repo');

test('PostsRepo', (assert) => {
  function newPostsRepo(fetch) {
    return PostsRepo('/', fetch, Cache());
  }

  assert.test('fetch()', async () => {
    const expectedPosts = [1, 2, 3];
    const okFetch = () => Promise.resolve({
      status: 200,
      json: () => expectedPosts
    });
    assert.deepEqual(
      await newPostsRepo(okFetch).query(new Date()),
      {result: expectedPosts},
      'successfully fetches posts'
    );

    const failFetch = () => Promise.resolve({status: 500});
    assert.deepEqual(
      await newPostsRepo(failFetch).query(new Date()),
      {error: 'Cannot fetch posts'},
      'returns empty array and error on failure'
    );

    assert.end();
  });
});
#+END_SRC

Nice consequence of ditching proxyquire is that our tests run faster.

#+BEGIN_SRC sh :exports results :results output
(node src/global-state/good/posts-repo.test.js | ./node_modules/.bin/tap-spec) 2>&1
true
#+END_SRC

#+RESULTS:
#+begin_example

  PostsRepo


  fetch()

    ✔ successfully fetches posts
    ✔ returns empty array and error on failure


  total:     2
  passing:   2
  duration:  11ms


#+end_example

*** Caveat

Not every dependency has to become a parameter. Constant values, value objects,
and pure functions can be used without worry. Good example is lodash[fn:4].

** Doing too much or too many things

Also known as a failure to maintain single responsibility principle. Usual rule
of thumb is to look for names containing "and". But I find this problematic as
some people are good (or bad) at naming. It is possible to name =PersistentCache=
as =CacheAndSave=, but it does not mean that former is good and latter is
bad. It's hard to come up with example that is not ridiculous, but here we go.

#+BEGIN_SRC javascript
function UserRepo(store, mailer) {
  return {
    list() {
      return store.fetch('user:*');
    },
    fetch(id) {
      return store.fetch('user:' + id);
    },
    async update(id, data) {
      const old = await this.fetch(id);
      const result = await store.save('user:' + data.id, data);
      if (old.email != data.email) {
        await mailer.confirmEmail(id, data.email);
      }
      return result;
    },
    async save(data) {
      const id = await store.nextId();
      const result = await store.save('user:' + id, data);
      await mailer.confirmEmail(id, data.email);
      return result;
    }
  };
}
#+END_SRC

Besides the funky key value store, we have repository initiating email
confirmation. On it's own, this only feels wrong, but might be completely
benign. Why does it feel wrong? First, =mailer= is used only in two of four
methods. Maybe it would make sense to split =UserRepo= into reader and writer
parts? Queries and commands? Invocation of confirmation flow also raises some
questions. Since we are passing user ID, is =mailer= supposed to understand it's
meaning? Will we have to encode confirmation link inside =mailer=? Does it mean
that =mailer= will have to understand routing? Oh my... It seems that =mailer= is
not supposed to be here, and it's interface has to be different.

Where should we put it? Let's help ourselves by imagining that we also have
account registration form, and profile view. Now, =mailer= makes sense in a
registration form, but profile screen does not need it. So we are going to move
=mailer= to registration handler. It makes sense that request handler knows how to
construct links, thus we can build email message with confirmation URL
there. We'll pass it to =mailer= via generic interface, for example
=mailer.send(recepients, subject, body)=.

To solve this puzzle of responsibilities, we asked some questions and gave
ourselves hypothetical answers. In real world, question will have real answers,
which will lead to other (but possibly similar) solutions. Main takeaway: use
your head and don't overdo it. Sometimes things are not easily separable. Think
about your domain.

** TODO Business Logic in Constructors

This one is my favourite.

* Epilogue

Knowing all this, what should I conclude about modern web development using
React framework? Recently I came to conclusion that it is a step down compared
to AngularJS when it comes to writing testable code. I'm still writing tests and
looking at tests written by others, but I notice that tests are usually littered
with special libraries that does module rewriting, like proxyquire. We already
touched upon global state issues that might be hiding behind this.

It's not completely fair to blame React for poor testing practices, but let's
say AngularJS did it better by having dependency injection pattern at it's
core. React won in the end by outdoing AngularJS in almost everything else.

* Footnotes

[fn:6] Common term used to refer to functions querying, for example, Redux state.

[fn:5] To be honest, AngularJS is not perfect, but it has really great testing story.

[fn:4] https://github.com/lodash/lodash

[fn:3] https://github.com/thlorenz/proxyquire

[fn:2] http://misko.hevery.com/code-reviewers-guide/

[fn:1] https://www.youtube.com/playlist?list=PLD0011D00849E1B79

